1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

  Ans: Numerical python is designed specifically for scientific computation and data analysis. it provides efficient array operations which are essential for hadling large dataset, performing complex mathematical computation and enhancing the performance of python in scientific applications.
  it enhances capabilities of python in following ways:
  1. multidimensional array- numpy provides ndarray data structures which allows the creation of high high performance multi dimensional arrays. unlike python list(heterogeneous data type) numpy array have a fixed size and hold element of same data type, making them to process efficiently and faster.
  2.Element wise operation and broad casting - coplex nested loops not required as operations are automatically applied acress element in an array without the requiremnt of the loop. broadcasting allows operations on array






2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?
Ans: np.mean() function is used when we will have to calculate arithmetic mean of the ie average of the element along a specified axis or of the entire array. it does not support weight of the array
np. average() function is used when the weighted average if weights are provided. otherwise it will behave like np.mean() function. it supppors weights so its useful when if you want to give different element varying level of importance.


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
Ans: to reverse a numpy arrays along different axes  for 1D array slicing with the [::-1] is used.
np.flip() function to reverse 2D array along specific axes is used.


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
the .dtype attribute reveals the data type which could be an integer type, float type or others like complex bool or custom data types.
each data type has a specific size. the int size of diff numbers take different bytes. so if we use small int number it will occupy less memory. this is particularly important when we work with large array as it can reduce memory usage significantly making it possible to handle large dataset within memory constarints. smaller data types require less computational overheads that are more efficient than python loops.choosing right data type improves computational speed.


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
ndarray is powerful flexible and efficient  multi dimensional arrays data structure. these array generalize 1 dimensional and 2 dimensional arrays into higher dimensional making them highly versatile for handling complex dataset.

python list:
1D structure(nested for multidimensions)  heterogeheous data type
less efficient as element are reference to memory locations.
slower requiring loops for element wise operations.
basic slicing and indexing no broadcasting

Numpy ndarray:
multi dimensional homogeneous data type.
more memory efficient stored in continous blocks
much faster for large data types
slicing indexing and broadcasting

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
Ans: numpy array is used when you need to work with large numerical datasets and needing fast computation and efficient memory usage, especially for scientific and mathematical tasks.
stores homogeneous data types, this allows for more eficient memory usage and faster computation.
numpy array provide a wide array for of mathematical and statistical functions, optimized for fast computation.
provide more advanced slicing such as slicing multi dimensional arrays and support boolean indexing and masking which is powerful for data selection.
memory efficient since it stores data in contiguous blocks
supports multi dimensional array which make it very flexible for scientific computing
support elementwise operation directly eg. addition subtraction multiplication, thats the reason it is convenient for data computation.
much faster for large dataset and mathematical operation.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.
vstack() the v stack function stacks array in vertical sequence (row wise)
syntax is numpy.vstack((array1,array2,...))
import numpy as np
a=np.array([1,2])
b=np.array([3,4])
result=np.vstack((a,b))
print result
[[1 2]
[3 4]]

hstack() vstack function joins array along a new axis wich can be specified.
in this we have to specify axis to stack along which add an additional dimension to an array


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
Ans: flipplr() function flips an array horizontally or along left right axis. it only works for 2D arrays or higher and reverses the order of column in each row does not allow to flip along any other axis but horizontal
flipud() function flips an array along the vertical axis, it reverses the order of the rows


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
Ans: array_split() method is used to split an array into multiple subarray. number of parts can be specified while splitting. it handle caseswhere an array can not be evenly divided into the specified number of subarrays. if attays can not be divided equally then it will crate sun arrays of slightly different size with the earlier sub arrays having one extra element.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
Ans:
vectorization refers to the process of applying operations over the entire array(vector) at once rather than looping over individual element. vectorised
operations are very efficient as compare to python for loops.
the vectorized code is simpler and runs faster.
broadcasting is a method thst allow numpy to perform array of different shape by stretching the smaller array of different shapesby stretching the smaller array. along certail axis to make their shape compatible. broadcasting allows element wise operation between arrays of different shapes without creating additional copies of data.


In [6]:
# Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np
array_1=np.random.randint(1,100,(3,3))
# Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np
array_1=np.random.randint(1,100,(3,3))
print(array_1)
array_2=np.transpose(array_1)
print(array_2)

[[ 7 88 31]
 [66 34  5]
 [10  9 69]]
[[ 7 66 10]
 [88 34  9]
 [31  5 69]]


In [9]:
# Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np
array_1=np.arange(10)
print(array_1)
array_2=array_1.reshape(2,5)
print(array_2)
array_3=array_2.reshape(5,2)
print(array_3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
#Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np
array_1=np.random.rand(4,4)
print(array_1)
array_2=np.pad(array_1,pad_width=1,mode='constant',constant_values=0)
print(array_2)




[[0.72470024 0.05924145 0.29147944 0.94025219]
 [0.66158722 0.61976177 0.1888786  0.04114923]
 [0.04848935 0.85285028 0.4522678  0.07168414]
 [0.49845595 0.72415739 0.97418956 0.80463365]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.72470024 0.05924145 0.29147944 0.94025219 0.        ]
 [0.         0.66158722 0.61976177 0.1888786  0.04114923 0.        ]
 [0.         0.04848935 0.85285028 0.4522678  0.07168414 0.        ]
 [0.         0.49845595 0.72415739 0.97418956 0.80463365 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [11]:
# Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np
array_1=np,np.arange(10,60,5)
print (array_1)

(<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>, array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55]))


In [14]:
# Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.
import numpy as np
array_1=np.array(['python','numpy','pandas'])
print(array_1)
array_2=np.char.upper(array_1)
print(array_2)
array_3=np.char.lower(array_1)
print(array_3)
array_4=np.char.title(array_1)
print(array_4)



['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [16]:
#Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np
array_1=np.array(['python','numpy','pandas'])
print(array_1)
array_2=np.char.join('',array_1)
print(array_2)


['python' 'numpy' 'pandas']
['python' 'numpy' 'pandas']


In [30]:
#Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np
array_1=np.array([1,2,3,4])
print(array_1)
array_2=np.array([5,6,7,8])
print(array_2)
array_3=array_1+array_2
print(array_3)
array_4=array_2-array_1
print(array_4)
array_5=array_2*array_1
print(array_5)
array_6=array_2/array_1
print(array_6)

[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]
[4 4 4 4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]


In [31]:
#Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np
array_1=np.eye(5)
print(array_1)
array_2=np.diag(array_1)
print(array_2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [36]:
# Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array.
import numpy as np
array_1=np.random.randint(0,1000,100)
print(array_1)
def is_prime(num):
  if num<2:return False
  for i in range(2,int(num**0.5)+1):
    if num%i==0:
      return False
      return true
      array_2=[num for num in array_1 if i is prime]
      print(array_2)






[572 258 220 327 293 796 690 677 231 319 361 871 592 979 283 846 930 571
  62 896 649 805 266 466 238 598 556 113 312 619 743 180 427 716 515 700
 188 184 622 105 554 522 324 732 727 347 293 599 612 691 831 105 245 718
 377 429 500 237 483 302 987 629 229 389 588 574  70 353 761 854 172 558
 989 591 273 644 192   0 705 784 968 886 404 449 813 421 147 379  36 174
 860 205 747  29  35 304 983 131 937 365]


In [40]:
#Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages.
import numpy as np
temp=np.random.uniform(20,30,40)
print(temp)
weekly_avg=np.mean(temp.reshape(-1,10),axis=1)
print(weekly_avg)



[21.98473038 24.79300194 26.3774638  21.56893125 27.85241395 29.60444908
 27.25717465 25.6710283  26.98220604 26.33659728 26.34038728 26.78180174
 24.06572265 27.78464918 23.49784157 28.42322603 21.09984971 20.8527804
 21.40421767 28.87034086 23.19441052 27.01094923 28.2485371  23.04930422
 21.43246164 28.41174836 21.89022726 23.6644481  28.34718303 25.32798306
 24.03936955 21.5938263  22.88310453 28.20373316 23.29942963 26.49064636
 22.95773824 27.81022959 27.87007231 27.58751203]
[25.84279967 24.91208171 25.05772525 25.27356617]
